generate_reveal_slides:
  description: >
    제공된 마크다운 리포트를 심층 분석한 후, reveal.js 호환 마크다운 슬라이드 프레젠테이션을 완성도 높게 생성하세요.
    
    **1단계: 리포트 구조 분석**
    - 리포트의 주요 섹션, 핵심 포인트, 중요한 데이터 포인트를 식별
    - 별도 슬라이드에서 강조되어야 할 중요한 내용 파악
    - 논리적 흐름을 고려한 매력적인 프레젠테이션 세그먼트 구조 설계
    - 독자 관점에서 이해하기 쉽고 임팩트 있는 슬라이드 플로우 계획
    
    **2단계: Reveal.js 슬라이드 생성**
    - 분석된 구조를 바탕으로 reveal.js 호환 마크다운 슬라이드 생성
    - 수평 슬라이드(---)와 수직 슬라이드(--)를 포함한 적절한 reveal.js 마크다운 구문 사용
    - 헤더, 불릿 포인트, 적절한 강조가 포함된 올바른 형식 적용
    - 전환 효과를 포함하고 프레젠테이션 전체에서 시각적 일관성 유지
    
    리포트 내용: {report_content}
    사용자 정보: {user_info}
    
    **핵심 지침**: 사용자 정보가 제공되면 프레젠테이션에 포함하세요:
    - 제목 슬라이드에서 user_info.name을 발표자 이름으로 사용
    - 관련 있는 경우 user_info.position과 user_info.department 포함
    - 적절한 경우 사용자 컨텍스트로 프레젠테이션 개인화
  expected_output: >
    다음을 포함하는 완전한 reveal.js 마크다운 형식 슬라이드 프레젠테이션:
    
    **필수 슬라이드 구성:**
    1. **제목 슬라이드** - 주제, 발표자 이름(user_info에서), 메타데이터 포함
    2. **목차/안건 슬라이드** - 프레젠테이션 전체 구조 안내
    3. **주요 내용 슬라이드들** - 제목과 핵심 포인트가 있는 각 섹션별 슬라이드
    4. **결론 슬라이드** - 요약 및 마무리
    
    **기술적 요구사항:**
    - 적절한 reveal.js 구문(새 슬라이드용 ---, 수직 슬라이드용 --)
    - 불릿 포인트, 헤더, 강조 형식 적절히 활용
    - 논리적 슬라이드 전환과 흐름
    - 깔끔하고 전문적인 프레젠테이션 구조
    - 적절한 경우 사용자 정보 통합(발표자 이름, 부서 등)
    
    **리포트 내용에서 파악한 실제 주제와 내용을 중심으로 슬라이드를 구성하세요.**
    결과물은 reveal.js 프레젠테이션 프레임워크와 직접 사용할 수 있도록 준비되어야 합니다.
  agent: slide_generator 