generate_field_value:
  description: >
    field_info에 제공된 특정 폼 필드에 대해서만 현실적이고 상세하며 의미 있는 값을 생성하세요.
    세심함과 디테일에 대한 주의를 보여주는 전문적이고 고품질의 값을 생성하세요.
    
    **중요**: '{topic}'은 워크플로우 단계명입니다 (주제 제목이 아님). 리포트 내용이 실제 주제와 맥락을 담고 있으므로 이 내용을 절대적으로 참조하세요.
    
    리포트 내용: {report_content}
    워크플로우 단계: {topic}
    필드 정보: {field_info}
    사용자 정보: {user_info}
    이전 작업 컨텍스트: {previous_context}
    
    **핵심 규칙 - 정확히 따라야 함**:
    1. **엄격한 필드 매칭**: field_info에 지정된 정확한 필드 키에 대해서만 값 생성
    2. **추가 필드 금지**: 요청된 것 이외의 추가 필드, 중첩 객체, 구조 생성 금지
    3. **정확한 키 사용**: 각 field_info 항목의 정확한 "key"를 JSON 키로 사용
    4. **고품질 값**: 상세하고 의미 있는 전문적 값 생성 - 일반적인 플레이스홀더 아님
    5. **맥락 인식**: 리포트 내용이 비어있으면 이전 작업 컨텍스트로 문맥 및 흐름을 파악하고 단계명에 맞게 고품질 값 생성
    
    **값 생성 전략**:
    - **이전 컨텍스트 활용**: 이전 작업에서 요구사항 및 목적, 결과물을 분석하여 현재 액티비티에 맞는 결과물을 생성
    - **사용자 관련 필드** (이름, 신청자, 부서, 직급, 이메일): 가능한 경우 정확한 user_info 값 사용
    - **날짜 필드** ("date", "start", "end", "time" 포함): 적절한 한국어 형식으로 현실적이고 구체적인 날짜 생성
    - **유형/카테고리 필드** ("type", "category", "kind" 포함): 맥락상 관련 있고 구체적인 값 생성
    - **이유/목적 필드** ("reason", "purpose", "description" 포함): 상세하고 전문적인 설명 생성
    - **기간 필드**: 적절한 한국어 형식으로 구체적이고 현실적인 기간 생성
    - **연락처 필드**: 맥락에 따른 적절한 연락처 정보 생성
    - **기타 필드**: 의미적으로 분석하여 상세하고 맥락에 적합한 값 생성
    
    **품질 기준**:
    - 값은 일반적이지 않고 상세하고 구체적이어야 함 (예: "5일"이 아닌 "2024년 12월 23일부터 12월 27일까지 (5일간)")
    - 적절한 한국어 비즈니스 언어와 형식 사용
    - 맥락에 맞는 현실적인 시나리오 생성
    - 리포트 내용이 없으면 단계명과 필드 맥락을 기반으로 고품질 값 생성
    
    **중요**: field_info에는 "key", "type", "text" 속성이 있는 객체들이 포함됩니다.
    "key"를 JSON 키로 사용하고 "text"를 생성할 상세한 값의 종류를 이해하는 맥락으로 사용하세요.
    제공된 모든 사용자 정보는 정확히 보존되어야 합니다.
  expected_output: >
    요청된 필드 키와 고품질로 생성된 값만 포함하는 평면 JSON 객체.
    field_info의 정확한 "key"를 JSON 키로 사용하세요.
    
    **엄격한 형식 예시**:
    {{
      "field_key_1": "상세하고_의미있는_값_1",
      "field_key_2": "상세하고_의미있는_값_2"
    }}
    
    **절대 요구사항**:
    - 요청된 것 이외의 중첩 객체나 추가 필드 금지
    - "user_related_fields", "generated_fields" 또는 그룹화 구조 금지
    - field_info에 제공된 모든 필드 키에 대한 값 생성
    - field_info에 제공된 필드 키에 대해서만 값 생성
    - 각 값은 상세하고 전문적이며 맥락에 적합해야 함
    - 출력은 유효한 JSON 형식이어야 함
    - user_info 값을 절대 변경하거나 수정하지 말고 제공된 그대로 사용하세요! 