analyze_topic:
  description: >
    Analyze the topic "{topic}" to identify key components, subtopics, relevant industries, technologies, applications, and challenges.
    Consider the scope, audience, and purpose of a comprehensive report on this topic.
    Identify what aspects of the topic would be most important to cover in a detailed report.
  expected_output: >
    A comprehensive analysis of the topic that identifies key components, subtopics, and important areas to cover in the report.
    Include insights on the scope, breadth, and depth appropriate for this topic.
  agent: topic_analyzer

create_outline:
  description: >
    Create a detailed outline for a comprehensive report on {topic}.
    Use the topic analysis provided to structure a logical flow of sections and subsections.
    Each section should have a clear title and a brief description of what it will cover.
    Each section should be assigned a unique ID for reference.
    The outline should be comprehensive, covering all important aspects of the topic.
  expected_output: >
    A structured outline in JSON format with sections and their titles, descriptions, and IDs. Example format:
    {
      "toc": [
        {"id": "intro", "title": "Introduction", "description": "Overview of [topic] and its importance"},
        {"id": "background", "title": "Background and Context", "description": "Historical development and context of [topic]"},
        ...
      ]
    }
  agent: outline_builder

configure_agents:
  description: >
    For each section in the report outline, configure appropriate AI agents with specialized roles, goals, and backstories.
    These agents will be responsible for researching and writing their respective sections.
    Each agent configuration should include role, goal, and backstory suitable for the specific section.
  expected_output: >
    A JSON object containing agent configurations for each section in the outline, keyed by section ID. Example format:
    {
      "agent_configs": [
        {
          "section_id": "intro",
          "role": "Introduction Specialist",
          "goal": "Create an engaging introduction that...",
          "backstory": "You are an expert in..."
        },
        ...
      ]
    }
  agent: agent_configurator

configure_tasks:
  description: >
    For each section in the report outline, define research and writing tasks with clear instructions.
    Each task should have a description and expected output suitable for the specific section.
    Consider how the section fits into the overall report structure.
  expected_output: >
    A JSON object containing task configurations for each section in the outline, keyed by section ID. Example format:
    {
      "task_configs": [
        {
          "section_id": "intro",
          "research_task": {
            "description": "Research key facts and context for introduction to [topic]...",
            "expected_output": "A comprehensive research brief covering..."
          },
          "writing_task": {
            "description": "Write an engaging introduction for [topic] that...",
            "expected_output": "A polished introduction section that..."
          }
        },
        ...
      ]
    }
  agent: task_configurator

compile_planning_output:
  description: >
    Compile all planning outputs (outline, agent configurations, and task configurations) into a single structured format.
    Ensure that the structure is consistent and that all sections have appropriate agent and task configurations.
    The output will be used to dynamically create agents and tasks for the report writing phase.
  expected_output: >
    A complete, structured JSON object containing the table of contents, agent configurations, and task configurations for the entire report.
    The format should follow:
    {
      "toc": [...],
      "agent_configs": [...],
      "task_configs": [...]
    }
    Ensure all IDs are consistent across the different components.
  agent: task_configurator 