apiVersion: apps/v1
kind: Deployment
metadata:
  name: polling-service-deployment
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  # 새로운 파드가 준비될 때까지 기존 파드를 유지
  selector:
    matchLabels:
      app: polling-service
  template:
    metadata:
      labels:
        app: polling-service
    spec:
      terminationGracePeriodSeconds: 300  # 5분 grace period
      containers:
      - name: polling-service
        image: ghcr.io/uengine-oss/process-gpt-polling-service:latest
        ports:
        - containerPort: 8000
        lifecycle:
          preStop:
            exec:
              command: ["python", "-c", "import signal; import os; os.kill(1, signal.SIGTERM)"]
        readinessProbe:
          exec:
            command: ["python", "-c", "import psutil; exit(0 if psutil.pid_exists(1) else 1)"]
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          exec:
            command: ["python", "-c", "import psutil; exit(0 if psutil.pid_exists(1) else 1)"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: OPENAI_API_KEY
              name: openai-secret
        - name: SUPABASE_URL
          valueFrom:
            configMapKeyRef:
              key: SUPABASE_URL
              name: my-config
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              key: SERVICE_ROLE_KEY
              name: my-secrets
        - name: SUPABASE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: my-secrets
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: DB_NAME
              name: my-secrets
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: DB_USER
              name: my-secrets
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: my-secrets
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: my-secrets
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: DB_PORT
              name: my-secrets
        - name: EXECUTION_SERVICE_URL
          value: http://execution-service:8000
        - name: MEMENTO_SERVICE_URL
          value: http://memento-service:8005
        - name: ENV
          value: production
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi