apiVersion: apps/v1
kind: Deployment
metadata:
  name: polling-service-deployment
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  # 새로운 파드가 준비될 때까지 기존 파드를 유지
  selector:
    matchLabels:
      app: polling-service
  template:
    metadata:
      labels:
        app: polling-service
    spec:
      terminationGracePeriodSeconds: 300  # 5분 grace period
      containers:
      - name: polling-service
        image: ghcr.io/uengine-oss/process-gpt-polling-service:latest
        ports:
        - containerPort: 8000
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "echo 'Graceful shutdown initiated'; sleep 10"]
        readinessProbe:
          exec:
            command: ["python", "-c", "import requests; import os; url=os.getenv('SUPABASE_URL'); exit(0 if url else 1)"]
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          exec:
            command: ["python", "-c", "import psutil; import os; pid=1; exit(0 if psutil.pid_exists(pid) else 1)"]
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: OPENAI_API_KEY
              name: openai-secret
        - name: SUPABASE_URL
          valueFrom:
            configMapKeyRef:
              key: SUPABASE_URL
              name: my-config
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              key: SERVICE_ROLE_KEY
              name: my-secrets
        - name: SUPABASE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: my-secrets
        - name: SMTP_SERVER
          value: smtp.gmail.com
        - name: SMTP_PORT
          value: 587
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              key: SMTP_USERNAME
              name: my-secrets
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SMTP_PASSWORD
              name: my-secrets
        - name: EXECUTION_SERVICE_URL
          value: http://execution-service:8000
        - name: MEMENTO_SERVICE_URL
          value: http://memento-service:8005
        - name: ENV
          value: production
        - name: LANGSMITH_API_KEY
          valueFrom:
            secretKeyRef:
              key: LANGSMITH_API_KEY
              name: langsmith-secrets
        - name: LANGSMITH_PROJECT
          valueFrom:
            secretKeyRef:
              key: LANGSMITH_PROJECT
              name: langsmith-secrets
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi